version: '2.0'

services:
    serve:
        build: https://raw.githubusercontent.com/pdxwebdev/yadacoin/master/docker/serve/Dockerfile
        ports: 
          - 8000:8000
        environment:
          - PYTHONUNBUFFERED=0
        volumes:
          - ./config:/config
        depends_on:
          - mongodb
    consensus:
        build: https://raw.githubusercontent.com/pdxwebdev/yadacoin/master/docker/consensus/Dockerfile
        environment:
          - PYTHONUNBUFFERED=0
        volumes:
          - ./config:/config
        depends_on:
          - mongodb
    mine:
        build: https://raw.githubusercontent.com/pdxwebdev/yadacoin/master/docker/mine/Dockerfile
        environment:
          - PYTHONUNBUFFERED=0
        volumes:
          - ./config:/config
        depends_on:
          - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        user: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
          - 27017:27017
        command: mongod --logpath=/dev/null # --quiet